FROM golang:1.25-alpine as builder

ARG TARGETARCH
ARG RELEASE

WORKDIR /go/src/github.com/lgcorzo/mc
COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=${TARGETARCH} go build -tags kqueue -trimpath -o /go/bin/mc .

FROM registry.access.redhat.com/ubi8/ubi-micro:latest

ARG TARGETARCH
ARG RELEASE

LABEL maintainer="lgcorzo <dev@lgcorzo>"

COPY CREDITS /licenses/CREDITS
COPY LICENSE /licenses/LICENSE

COPY --from=builder /go/bin/mc /usr/bin/mc

RUN chmod +x /usr/bin/mc

ENTRYPOINT ["mc"]
