# Stage 1: Source build for release
FROM golang:1.25-alpine AS build

WORKDIR /build
RUN apk add --no-cache ca-certificates git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ARG TARGETOS TARGETARCH
ENV CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH}

RUN go build -v -trimpath -ldflags="-s -w" -o /go/bin/mc .

# Stage 2: UBI Minimal Runtime
FROM registry.access.redhat.com/ubi9/ubi-micro:latest

ARG TARGETARCH
ARG RELEASE

LABEL maintainer="Luis Corzo <lgcorzo@phdata.internal>"

COPY CREDITS /licenses/CREDITS
COPY LICENSE /licenses/LICENSE
COPY --from=build /go/bin/mc /usr/bin/mc

USER 10001:10001

ENTRYPOINT ["mc"]
